### PR TITLE
Additional updates to SP2 and SP5

### PR DESCRIPTION
**Pull request by tiffanynolan**
Made some changes to update the add client steps in both, plus some other wording changes, additions, etc. to SP5 as I was trying to review the first few tasks.

### CODE REVIEW

**Comment by tiffanynolan** [comment]
I'll be on PTO until Monday, so feel free to make any additional changes, merge, etc.

**Review by evanshortiss — APPROVED** [review]
LTGM 👍

**Comment by evanshortiss** [comment]
One thing I might add is that the mobile SP will change soon, so we probably don't need to invest too much time in the current version.

**Review by wtrocki — APPROVED** [review]
LGTM - checked only mobile one

**Pull request merged**
