### PR TITLE
lock root filesystems of WT pods

### PR DESCRIPTION
**Pull request by pb82**

### CODE REVIEW

**Comment by jessesarn** [comment]
@tiffanynolan want to get this in for https://issues.redhat.com/browse/INTLY-9765
cc @ciaran-byrne

**Comment by Rajagopalan-Ranganathan** [comment]
Tested the changes with @pb82 and everything worked. please see the test instructions in the following comment

**Comment by Rajagopalan-Ranganathan** [comment]
To test from the PR branch: start from top of the instructions, For testing after the changes are merged start
from section ```testing the changes```
User: kubeadmin

### ** Env:**
1) OSD cluster with RHMI operator running.
2) Stop the operator.
3) Go to project/namespace: redhat-rhmi-solution-explorer-operator
3) Choose deployments and scale it down to 0.

**Setting the Walkthrough locations:**

1) Select namespace: redhat-rhmi-solution-explorer
2) go to Pods
3) select the tutorial-web-app-<XXX> pod
4) select environment
5) Edit the field: WALKTHROUGH_LOCATIONS with the value: https://github.com/integr8ly/solution-patterns.git#INTLY-9765

You should see the containers are recreated.


### **Testing the changes:**


User: test IDP User
Ex: test-user01/Password1

Make sure the RHMI operator is running again.
If you do not have test IDP set up, run the below command from the root of the integr8ly operator repo:

```PASSWORD=Password1 DEDICATED_ADMIN_PASSWORD=Password1 ./scripts/setup-sso-idp.sh```

Now the test IDP is set.

Login back to console as the test user.

**Walk through test:**

Follow the link to solution explorer (from the grid like menu icon on the top right hand - next to the + ? username)

Login with test IDP user

1) Select All solution patterns
2) Finish testing by completing the first Walk through (1 - Connecting Applications using asynchronous messaging)

**Comment by pb82** [comment]
thanks @Rajagopalan-Ranganathan

**Pull request merged**
